### ISSUE TITLE
The server is down when chromium-browser is missing 

### ISSUE THREAD

**Issue by kanevk** [scdekov/pi-home-media#4]
```
Error: spawn chromium-browser ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
I suggest adding it as a dependency..

**Comment by scdekov** [comment]
good, but where? I think it can't be installed through npm.
